stages:
  - build
  - test

build:
  stage: build
  tags:
  - node
  cache:
    paths:
    - node_modules/
  script:
  - npm install
  - npm run build
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_{$CI_COMMIT_SHA}"
    expire_in: 3d
    paths:
    - dist/
    - node_modules/
    - config/

test:
  stage: test
  tags:
  - node
  dependencies:
  - build
  script:
  - npm test